# -*- coding: utf-8 -*-
"""
=============================================================================
ABAQUS Python Script - Stochastic Mesoscale Laminate Partitioning (2D)
=============================================================================
Article: "Unraveling Transverse Crack Multiplication in Thin-Ply Orthotropic
          Laminates: A Stochastic Finite Element Study"
Journal: Mechanics of Advanced Materials and Structures (2025)

ANALYSIS TYPE: 2D PLANE (Cross-section analysis)
  - X axis = length direction (longitudinal)
  - Y axis = thickness direction
  - Element type: quadrilateral (CPE4R plane strain or CPS4R plane stress)
  - Cohesive elements: COH2D4

Compatibility: ABAQUS Python 2.7
  - NO f-strings (uses .format() and % formatting)
  - NO Python 3-only features
  - Tested on ABAQUS 6.17+

Stage: Geometry creation + Partitioning ONLY
       (Materials, mesh, BC, analysis come in next stages)

Author: Generated by Z.ai
Date: 2026-07-15

How to run:
  1. Open ABAQUS CAE
  2. File > Run Script... > select this file
  3. Or from command line: abaqus cae script=this_file.py
=============================================================================
"""

from abaqus import *
from abaqusConstants import *
import part
import mesh
import regionToolset
import logging

# ============================================================
# USER INPUTS - ویرایش این مقادیر
# ============================================================

# --- ورودی‌های هندسی (Geometry inputs) - 2D ---
L = 80.0            # طول نمونه [mm] (محور X)
L_gauge = 70.0      # طول gauge [mm] (ناحیه قرارگیری cohesive columns)
# NOTE: عرض (W) حذف شد - تحلیل 2D است

# --- ورودی‌های لایه (Ply inputs) ---
t0 = 0.250          # ضخامت هر لایه 0° [mm] - ورودی شما
t90 = 0.250         # ضخامت هر لایه 90° [mm] - ورودی شما
n90 = 2             # تعداد لایه‌های 90° - ورودی شما

# --- نوع لایه‌چینی (Layup type) ---
# 'symmetric'  => [0/90n]s = 0 / 90*n / 90*n / 0
# 'asymmetric' => [0/90/0] = 0 / 90*n90 / 0
layup_type = 'symmetric'

# --- نوع تحلیل 2D (2D analysis type) ---
# 'PLANE_STRAIN'  => CPE4R elements (برای laminate با عرض زیاد)
# 'PLANE_STRESS'  => CPS4R elements (برای laminate با عرض کم)
analysis_type = 'PLANE_STRAIN'

# --- پارامترهای Stochastic ---
n_cells_thickness = 5    # تعداد زیرسلول‌های هر لایه 90° در ضخامت
rho = 0.5                # چگالی اشباع ترک [cracks/mm] - از Ref [17]

# --- تنظیمات مدل ---
model_name = 'Laminate_Model'
part_name = 'Laminate'

# ============================================================
# COMPUTE LAYUP SEQUENCE
# ============================================================

def build_layup(layup_type, n90, t0, t90):
    """ساخت دنباله لایه‌چینی از پایین به بالا."""
    layup = []
    if layup_type == 'symmetric':
        layup.append((0, t0))
        for i in range(n90):
            layup.append((90, t90))
        for i in range(n90):
            layup.append((90, t90))
        layup.append((0, t0))
    elif layup_type == 'asymmetric':
        layup.append((0, t0))
        for i in range(n90):
            layup.append((90, t90))
        layup.append((0, t0))
    else:
        raise ValueError("layup_type must be 'symmetric' or 'asymmetric'")
    return layup


def print_layup_info(layup, t0, t90, n90, layup_type):
    """نمایش اطلاعات لایه‌چینی."""
    print("")
    print("=" * 70)
    print("LAYUP INFORMATION - 2D Cross-section Analysis")
    print("=" * 70)
    print("Layup type: {}".format(layup_type))
    print("Analysis type: {}".format(analysis_type))
    print("Number of 90 plies (input n90): {}".format(n90))

    if layup_type == 'symmetric':
        n90_total = 2 * n90
        if n90 > 1:
            symbol = "[0/90{}]s".format(n90)
        else:
            symbol = "[0/90]s"
    else:
        n90_total = n90
        if n90 > 1:
            symbol = "[0/90{}/0]".format(n90)
        else:
            symbol = "[0/90/0]"
    print("Layup symbol: {}".format(symbol))
    print("Total 90 plies: {}".format(n90_total))
    print("Total 0 plies: 2")
    print("")
    print("Layup sequence (bottom to top):")
    print("-" * 50)
    for i in range(len(layup)):
        angle = layup[i][0]
        t = layup[i][1]
        if angle == 0:
            direction = " longitudinal (fiber dir.)"
        else:
            direction = " transverse"
        print("  Ply {:2d}: {:3d} deg | t = {:.3f} mm |{}".format(i+1, angle, t, direction))
    print("-" * 50)
    total_t = 0.0
    for item in layup:
        total_t += item[1]
    print("Total thickness: {:.3f} mm".format(total_t))
    print("Specimen length: {:.3f} mm".format(L))
    print("Gauge length: {:.3f} mm".format(L_gauge))
    print("=" * 70)
    print("")


# ============================================================
# CREATE 2D BASE GEOMETRY - ساخت هندسه پایه 2D
# ============================================================

def create_base_geometry_2d(model_name, part_name, L, total_thickness):
    """
    ساخت پارت پایه به صورت 2D planar (سطح مقطع).
    X = طول نمونه, Y = ضخامت
    """
    # اگر مدل وجود دارد، حذف کن
    model_keys = mdb.models.keys()
    if model_name in model_keys:
        del mdb.models[model_name]
    mdb.Model(model_name)

    # اگر پارت وجود دارد، حذف کن
    part_keys = mdb.models[model_name].parts.keys()
    if part_name in part_keys:
        del mdb.models[model_name].parts[part_name]

    # ساخت اسکچ پروفایل (مستطیل در صفحه X-Y)
    s = mdb.models[model_name].ConstrainedSketch(
        name='__profile__',
        sheetSize=200.0)
    s.rectangle(point1=(0.0, 0.0), point2=(L, total_thickness))

    # ساخت پارت 2D planar (نه 3D)
    p = mdb.models[model_name].Part(
        name=part_name,
        dimensionality=TWO_D_PLANAR,
        type=DEFORMABLE_BODY)
    p.BaseShell(sketch=s)

    print("[OK] Created 2D part '{}': L={} mm x t={:.4f} mm".format(
        part_name, L, total_thickness))
    print("     X = length (0 to {})".format(L))
    print("     Y = thickness (0 to {:.4f})".format(total_thickness))
    print("     Analysis: 2D {}".format(analysis_type))
    return p


# ============================================================
# PARTITION THROUGH THICKNESS (horizontal lines)
# ============================================================

def partition_through_thickness(p, layup):
    """
    پارتیشن‌بندی در جهت ضخامت (Y) با خطوط افقی.
    NOTE: در ABAQUS 2D planar، DatumPlaneByPrincipalPlane استفاده می‌شود
    (نه DatumLineByPrincipalPlane) و PartitionFaceByDatumPlane برای پارتیشن.
    """
    print("")
    print("--- Stage 1: Partitioning through thickness (ply boundaries) ---")

    # محاسبه Y مرزهای لایه‌ها
    y_boundaries = []
    y_current = 0.0
    for i in range(len(layup) - 1):
        angle = layup[i][0]
        t = layup[i][1]
        y_current += t
        y_boundaries.append((y_current, i + 1, angle))

    n_partitions = 0
    for item in y_boundaries:
        y = item[0]
        ply_idx_above = item[1]
        angle_above = item[2]

        # ساخت datum plane (XZPLANE offset در Y = y)
        # در 2D planar نیز DatumPlaneByPrincipalPlane استفاده می‌شود
        datum = p.DatumPlaneByPrincipalPlane(
            principalPlane=XZPLANE,
            offset=y)

        # پارتیشن همه faces با این datum plane
        # FIX: استفاده از p.faces به جای p.faces[:]
        try:
            p.PartitionFaceByDatumPlane(
                datumPlane=p.datums[datum.id],
                faces=p.faces)
        except Exception:
            # Fallback: استفاده از face list
            face_list = []
            for f in p.faces:
                face_list.append(f)
            p.PartitionFaceByDatumPlane(
                datumPlane=p.datums[datum.id],
                faces=face_list)

        n_partitions += 1
        print("  [{:2d}] Partition at Y = {:.4f} mm (boundary: Ply {} = {} deg)".format(
            n_partitions, y, ply_idx_above, angle_above))

    print("  -> Total through-thickness partitions: {}".format(n_partitions))


# ============================================================
# PARTITION 90° PLIES INTO SUB-CELLS
# ============================================================

def partition_90_ply_subcells(p, layup, n_cells_thickness):
    """
    تقسیم هر لایه 90° به n_cells_thickness زیرسلول در جهت ضخامت.
    """
    print("")
    print("--- Stage 2: Partitioning 90 plies into {} sub-cells ---".format(n_cells_thickness))

    # محاسبه Y-range هر لایه
    ply_info = []
    y_start = 0.0
    for i in range(len(layup)):
        angle = layup[i][0]
        t = layup[i][1]
        y_end = y_start + t
        ply_info.append({
            'index': i + 1,
            'angle': angle,
            'y_start': y_start,
            'y_end': y_end,
            'thickness': t,
        })
        y_start = y_end

    n_partitions = 0
    for ply in ply_info:
        if ply['angle'] != 90:
            continue

        dy = ply['thickness'] / n_cells_thickness
        print("  Ply {} (90 deg, t = {:.3f} mm):".format(ply['index'], ply['thickness']))
        print("    Y range: {:.4f} to {:.4f} mm".format(ply['y_start'], ply['y_end']))
        print("    Sub-cell thickness: {:.4f} mm".format(dy))

        for j in range(1, n_cells_thickness):
            y_partition = ply['y_start'] + j * dy
            datum = p.DatumPlaneByPrincipalPlane(
                principalPlane=XZPLANE,
                offset=y_partition)
            # FIX: استفاده از p.faces به جای p.faces[:]
            try:
                p.PartitionFaceByDatumPlane(
                    datumPlane=p.datums[datum.id],
                    faces=p.faces)
            except Exception:
                face_list = []
                for f in p.faces:
                    face_list.append(f)
                p.PartitionFaceByDatumPlane(
                    datumPlane=p.datums[datum.id],
                    faces=face_list)
            n_partitions += 1
            print("    [{:2d}] Sub-cell partition at Y = {:.4f} mm".format(
                n_partitions, y_partition))

    print("  -> Total 90 sub-cell partitions: {}".format(n_partitions))


# ============================================================
# PARTITION ALONG LENGTH (vertical lines - cohesive columns)
# ============================================================

def partition_along_length(p, layup, L, L_gauge, rho):
    """
    پارتیشن‌بندی در جهت طول (X) با خطوط عمودی برای مسیرهای cohesive.
    فقط در لایه‌های 90° و در ناحیه gauge انجام می‌شود.
    """
    print("")
    print("--- Stage 3: Partitioning along length (cohesive column paths) ---")

    # محاسبه t90_total
    t90_total = 0.0
    for item in layup:
        if item[0] == 90:
            t90_total += item[1]
    n_cohesive = int(round(rho * t90_total / L_gauge))
    n_cohesive = max(n_cohesive, 1)

    print("  Total 90 thickness: {:.4f} mm".format(t90_total))
    print("  rho (crack saturation): {:.3f} cracks/mm".format(rho))
    print("  Gauge length: {:.3f} mm".format(L_gauge))
    print("  n_cohesive = rho x t90_total / L_gauge = {} x {:.4f} / {} = {}".format(
        rho, t90_total, L_gauge, n_cohesive))

    # محاسبه موقعیت‌های gauge
    x_gauge_start = (L - L_gauge) / 2.0
    x_gauge_end = x_gauge_start + L_gauge
    print("  Gauge region: X = {:.3f} to {:.3f} mm".format(x_gauge_start, x_gauge_end))

    # محاسبه Y-range لایه‌های 90°
    y_ranges_90 = []
    y_start = 0.0
    for item in layup:
        angle = item[0]
        t = item[1]
        y_end = y_start + t
        if angle == 90:
            y_ranges_90.append((y_start, y_end))
        y_start = y_end

    if n_cohesive == 0:
        print("  WARNING: n_cohesive = 0, skipping along-length partitioning")
        return 0

    # توزیع یکنواخت cohesive columns در gauge length
    dx = L_gauge / (n_cohesive + 1)

    n_partitions = 0
    for i in range(n_cohesive):
        x_partition = x_gauge_start + (i + 1) * dx

        # ساخت datum plane (YZPLANE offset در X = x_partition)
        # در 2D planar نیز DatumPlaneByPrincipalPlane استفاده می‌شود
        datum = p.DatumPlaneByPrincipalPlane(
            principalPlane=YZPLANE,
            offset=x_partition)

        # پیدا کردن faceهای مربوط به لایه‌های 90° در ناحیه gauge
        # FIX: استفاده از getByBoundingBox به جای حلقه روی faces
        # این روش بسیار سریع‌تر و قابل اعتمادتر است
        y_min_90 = min(yr[0] for yr in y_ranges_90)
        y_max_90 = max(yr[1] for yr in y_ranges_90)

        tol = 1e-6
        try:
            faces_to_partition = p.faces.getByBoundingBox(
                xMin=x_gauge_start - tol,
                yMin=y_min_90 - tol,
                zMin=-tol,
                xMax=x_gauge_end + tol,
                yMax=y_max_90 + tol,
                zMax=tol)
        except Exception:
            # Fallback: حلقه روی faces
            faces_to_partition = []
            for face in p.faces:
                try:
                    pt = face.pointOn[0]
                    cx = float(pt[0])
                    cy = float(pt[1])
                    for y_range in y_ranges_90:
                        y_min = y_range[0]
                        y_max = y_range[1]
                        if (y_min - 1e-6 <= cy <= y_max + 1e-6 and
                            x_gauge_start - 1e-6 <= cx <= x_gauge_end + 1e-6):
                            faces_to_partition.append(face)
                            break
                except Exception:
                    continue

        if len(faces_to_partition) > 0:
            try:
                p.PartitionFaceByDatumPlane(
                    datumPlane=p.datums[datum.id],
                    faces=faces_to_partition)
                n_partitions += 1
                print("  [{:2d}] Cohesive column {}/{} at X = {:.3f} mm ({} faces)".format(
                    n_partitions, i+1, n_cohesive, x_partition, len(faces_to_partition)))
            except Exception as e:
                print("  WARNING: Partition failed at X = {:.3f}: {}".format(x_partition, e))

    print("  -> Total cohesive column partitions: {}".format(n_partitions))
    return n_cohesive


# ============================================================
# CREATE FACE SETS - ساخت مجموعه‌های وجهی
# ============================================================

def create_face_sets(p, layup):
    """
    ساخت setهای وجهی (face sets) برای لایه‌های 0° و 90°.
    از getByBoundingBox استفاده می‌شود که در ABAQUS قابل اعتمادتر از findAt است.
    """
    print("")
    print("--- Stage 4: Creating face sets ---")

    # محاسبه Y-range هر لایه
    ply_info = []
    y_start = 0.0
    for i in range(len(layup)):
        angle = layup[i][0]
        t = layup[i][1]
        y_end = y_start + t
        ply_info.append((angle, y_start, y_end))
        y_start = y_end

    total_t = y_end

    # پیدا کردن Y-range لایه‌های 0° و 90°
    y_min_0 = total_t
    y_max_0 = 0.0
    y_min_90 = total_t
    y_max_90 = 0.0

    for ply in ply_info:
        angle = ply[0]
        y_min = ply[1]
        y_max = ply[2]
        if angle == 0:
            y_min_0 = min(y_min_0, y_min)
            y_max_0 = max(y_max_0, y_max)
        else:
            y_min_90 = min(y_min_90, y_min)
            y_max_90 = max(y_max_90, y_max)

    tol = 1e-6
    L_total = 0.0
    for item in layup:
        L_total = max(L_total, L)  # L از متغیر سراسری
    # FIX: استفاده از L سراسری
    L_total = L

    # ساخت Ply_0_Set با getByBoundingBox
    print("  Creating Ply_0_Set (0° plies)...")
    try:
        faces_0 = p.faces.getByBoundingBox(
            xMin=-tol, yMin=y_min_0 - tol, zMin=-tol,
            xMax=L_total + tol, yMax=y_max_0 + tol, zMax=tol)
        if len(faces_0) > 0:
            p.Set(faces=faces_0, name='Ply_0_Set')
            print("  [OK] Created 'Ply_0_Set' with {} faces".format(len(faces_0)))
        else:
            print("  WARNING: No 0° faces found")
    except Exception as e:
        print("  WARNING: getByBoundingBox failed for 0°: {}".format(e))

    # ساخت Ply_90_Set با getByBoundingBox
    print("  Creating Ply_90_Set (90° plies)...")
    try:
        faces_90 = p.faces.getByBoundingBox(
            xMin=-tol, yMin=y_min_90 - tol, zMin=-tol,
            xMax=L_total + tol, yMax=y_max_90 + tol, zMax=tol)
        if len(faces_90) > 0:
            p.Set(faces=faces_90, name='Ply_90_Set')
            print("  [OK] Created 'Ply_90_Set' with {} faces".format(len(faces_90)))
        else:
            print("  WARNING: No 90° faces found")
    except Exception as e:
        print("  WARNING: getByBoundingBox failed for 90°: {}".format(e))

    # ساخت set برای هر زیرسلول 90°
    print("")
    print("  Creating sub-cell sets for stochastic Vf assignment:")

    # برای هر face در 90°، یک set جداگانه بساز
    # FIX: استفاده از getByBoundingBox برای هر sub-cell به جای findAt
    cell_counter = 0

    for ply_idx, ply in enumerate(ply_info):
        if ply[0] != 90:
            continue

        y_ply_start = ply[1]
        y_ply_end = ply[2]
        t_ply = ply[2] - ply[1]
        dy = t_ply / n_cells_thickness

        for j in range(n_cells_thickness):
            y_cell_min = y_ply_start + j * dy
            y_cell_max = y_ply_start + (j + 1) * dy

            try:
                faces_cell = p.faces.getByBoundingBox(
                    xMin=-tol, yMin=y_cell_min - tol, zMin=-tol,
                    xMax=L_total + tol, yMax=y_cell_max + tol, zMax=tol)

                if len(faces_cell) > 0:
                    cell_counter += 1
                    set_name = 'Cell_90_{:03d}'.format(cell_counter)
                    p.Set(faces=faces_cell, name=set_name)
            except Exception:
                continue

    print("  [OK] Created {} individual face sets (Cell_90_001 to Cell_90_{:03d})".format(
        cell_counter, cell_counter))


# ============================================================
# PRINT FINAL SUMMARY
# ============================================================

def print_summary(p, layup, n_cohesive, n_cells_thickness):
    """نمایش خلاصه نهایی پارت."""
    print("")
    print("=" * 70)
    print("PARTITIONING COMPLETE - 2D Model")
    print("=" * 70)
    print("Part name: {}".format(p.name))
    print("Total faces:    {:4d}".format(len(p.faces)))
    print("Total edges:    {:4d}".format(len(p.edges)))
    print("Total vertices: {:4d}".format(len(p.vertices)))
    print("Total datums:   {:4d}".format(len(p.datums)))

    n_plies = len(layup)
    n_90_plies = 0
    n_0_plies = 0
    for item in layup:
        if item[0] == 90:
            n_90_plies += 1
        elif item[0] == 0:
            n_0_plies += 1
    print("")
    print("Layup: {} plies ({} x 0 deg + {} x 90 deg)".format(
        n_plies, n_0_plies, n_90_plies))
    print("  90 sub-cells through thickness: {} per ply".format(n_cells_thickness))
    print("  Cohesive columns along length: {}".format(n_cohesive))
    print("  Analysis type: 2D {}".format(analysis_type))

    print("")
    print("=" * 70)
    print("NEXT STEPS - 2D Analysis")
    print("=" * 70)
    print("1. Assign materials (Section assignment):")
    print("   - Ply_0_Set  -> orthotropic elastic (2D)")
    if analysis_type == 'PLANE_STRAIN':
        print("   - Element type: CPE4R (4-node plane strain quadrilateral)")
    else:
        print("   - Element type: CPS4R (4-node plane stress quadrilateral)")
    print("   - Ply_90_Set -> orthotropic elastic with stochastic Vf per face")
    print("     (assign different Vf to Cell_90_001, Cell_90_002, ... based on micrograph)")
    print("2. Insert cohesive elements:")
    print("   - At vertical partition lines in 90 deg region")
    print("   - Element type: COH2D4 (4-node 2D cohesive)")
    print("3. Mesh the part:")
    print("   - Use quadrilateral elements")
    print("   - Refined mesh near cohesive paths")
    print("4. Apply boundary conditions and loads:")
    print("   - Tensile loading up to 2.5% strain (X direction)")
    print("   - Fix one end, displace the other")
    print("5. Submit job and post-process")
    print("=" * 70)


# ============================================================
# MAIN SCRIPT
# ============================================================

def main():
    """تابع اصلی - اجرای تمام مراحل پارتیشن‌بندی 2D."""

    print("")
    print("#" * 70)
    print("# ABAQUS SCRIPT: Stochastic Mesoscale Laminate (2D)")
    print("# Article: Transverse Crack Multiplication in Thin-Ply Laminates")
    print("# Analysis: 2D Cross-section (X-Y plane)")
    print("# Python 2.7 Compatible")
    print("#" * 70)

    # مرحله 0: ساخت لایه‌چینی
    layup = build_layup(layup_type, n90, t0, t90)
    print_layup_info(layup, t0, t90, n90, layup_type)

    # محاسبه ضخامت کل
    total_thickness = 0.0
    for item in layup:
        total_thickness += item[1]

    # مرحله 1: ساخت هندسه پایه 2D
    print(">>> Stage 0: Creating 2D base geometry...")
    p = create_base_geometry_2d(model_name, part_name, L, total_thickness)

    # مرحله 2: پارتیشن‌بندی در ضخامت (مرزهای لایه‌ها)
    partition_through_thickness(p, layup)

    # مرحله 3: پارتیشن‌بندی زیرسلول‌های 90°
    partition_90_ply_subcells(p, layup, n_cells_thickness)

    # مرحله 4: پارتیشن‌بندی در طول (مسیرهای cohesive)
    n_cohesive = partition_along_length(p, layup, L, L_gauge, rho)

    # مرحله 5: ساخت face sets
    create_face_sets(p, layup)

    # مرحله 6: خلاصه نهایی
    print_summary(p, layup, n_cohesive, n_cells_thickness)

    print("")
    print("[SUCCESS] 2D Script completed successfully!")


# ============================================================
# RUN
# ============================================================

if __name__ == '__main__':
    main()
else:
    main()
